//
//  BytecodeInstruction.swift
//  swiftjvm
//
//  Created by Daniel DeCovnick on 8/4/23.
//

import Foundation

struct BytecodeInstruction {
    enum Opcode : UInt8 {
        case nop
        case aconst_null
        case iconst_m1
        case iconst_0
        case iconst_1
        case iconst_2
        case iconst_3
        case iconst_4
        case iconst_5
        case lconst_0
        case lconst_1
        case fconst_0
        case fconst_1
        case fconst_2
        case dconst_0
        case dconst_1
        case bipush
        case sipush
        case ldc
        case ldc_w
        case ldc2_w
        case iload
        case lload
        case fload
        case dload
        case aload
        case iload_0
        case iload_1
        case iload_2
        case iload_3
        case lload_0
        case lload_1
        case lload_2
        case lload_3
        case fload_0
        case fload_1
        case fload_2
        case fload_3
        case dload_0
        case dload_1
        case dload_2
        case dload_3
        case aload_0
        case aload_1
        case aload_2
        case aload_3
        case iaload
        case laload
        case faload
        case daload
        case aaload
        case baload
        case caload
        case saload
        case istore
        case lstore
        case fstore
        case dstore
        case astore
        case istore_0
        case istore_1
        case istore_2
        case istore_3
        case lstore_0
        case lstore_1
        case lstore_2
        case lstore_3
        case fstore_0
        case fstore_1
        case fstore_2
        case fstore_3
        case dstore_0
        case dstore_1
        case dstore_2
        case dstore_3
        case astore_0
        case astore_1
        case astore_2
        case astore_3
        case iastore
        case lastore
        case fastore
        case dastore
        case aastore
        case bastore
        case castore
        case sastore
        case pop
        case pop2
        case dup
        case dup_x1
        case dup_x2
        case dup2
        case dup2_x1
        case dup2_x2
        case swap
        case iadd
        case ladd
        case fadd
        case dadd
        case isub
        case lsub
        case fsub
        case dsub
        case imul
        case lmul
        case fmul
        case dmul
        case idiv
        case ldiv
        case fdiv
        case ddiv
        case irem
        case lrem
        case frem
        case drem
        case ineg
        case lneg
        case fneg
        case dneg
        case ishl
        case lshl
        case ishr
        case lshr
        case iushr
        case lushr
        case iand
        case land
        case ior
        case lor
        case ixor
        case lxor
        case iinc
        case i2l
        case i2f
        case i2d
        case l2i
        case l2f
        case l2d
        case f2i
        case f2l
        case f2d
        case d2i
        case d2l
        case d2f
        case i2b
        case i2c
        case i2s
        case lcmp
        case fcmpl
        case fcmpg
        case dcmpl
        case dcmpg
        case ifeq
        case ifne
        case iflt
        case ifge
        case ifgt
        case ifle
        case if_icmpeq
        case if_icmpne
        case if_icmplt
        case if_icmpge
        case if_icmpgt
        case if_icmple
        case if_acmpeq
        case if_acmpne
        case goto
        case jsr
        case ret
        case tableswitch
        case lookupswitch
        case ireturn
        case lreturn
        case freturn
        case dreturn
        case areturn
        case `return`
        case getstatic
        case putstatic
        case getfield
        case putfield
        case invokevirtual
        case invokespecial
        case invokestatic
        case invokeinterface
        case invokedynamic
        case new
        case newarray
        case anewarray
        case arraylength
        case athrow
        case checkcast
        case instanceof
        case monitorenter
        case monitorexit
        case wide
        case multianewarray
        case ifnull
        case ifnonnull
        case goto_w
        case jsr_w
        case breakpoint = 0xca
        case impdep1 = 0xfe
        case impdep2 = 0xff
        
    }
}
